export {
  openai,
  compressToMp3,
  detectAudioFormat,
  convertToWav,
  ensureCompatibleFormat,
  type AudioFormat,
  voiceChat,
  voiceChatStream,
  textToSpeech,
  textToSpeechStream,
  speechToText,
  speechToTextWithTimestamps,
  type TimedTranscriptionSegment,
  type TimedTranscriptionWord,
  speechToTextWithSpeakers,
  speechToTextStream,
} from "./client";
