// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/recording-dashboard-redesign/ChildCentered.tsx": () => import("../components/mockups/recording-dashboard-redesign/ChildCentered.tsx"),
  "./components/mockups/recording-dashboard-redesign/Current.tsx": () => import("../components/mockups/recording-dashboard-redesign/Current.tsx"),
  "./components/mockups/slp-command-center/CommandCenter.tsx": () => import("../components/mockups/slp-command-center/CommandCenter.tsx")
};
